[package]
name = "chimera-md"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "0.11.0"
tokio = { version = "1", features = ["full"] }
axum = { version = "0.7.5", features = ["macros"] }
tower-http = { version = "0.5.2", features = ["fs", "trace"] }
handlebars = "5.1.2"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
serde = { version = "1.0.203", features = ["derive"] }
urlencoding = "2.1.3"
clap = { version = "4.5.6", features = ["derive", "env"] }
