[package]
name = "chimera-md"
version = "0.1.0"
edition = "2021"
authors = ["Alexander Barrentine", "Alexander Barrentine <acbarrentine@gmail.com>"]
description = "A markdown-aware web server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "0.11.0"
tokio = { version = "1", features = ["full"] }
axum = { version = "0.7.5", features = ["macros"] }
tower-http = { version = "0.5.2", features = ["fs", "trace"] }
handlebars = { version = "5.1.2", features = ["dir_source"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
serde = { version = "1.0.203", features = ["derive"] }
urlencoding = "2.1.3"
clap = { version = "4.5.6", features = ["derive", "env"] }
regex = { version = "1.10.5"}
tantivy = "0.22.0"
tempfile = "3.10.1"
walkdir = "2.5.0"
html2text = "0.12.5"
async-watcher = "0.3.0"
