# When used in Docker, these are probably the only fields you will want to change
site_title = "Chimera Example"
site_lang = "en"
generate_index = false

# But the rest of these are available if you want to tune things
document_root = "/data/www"
template_root = "/data/templates"
style_root = "/data/style"
icon_root = "/data/icon"
search_index_dir = "/data/search"
log_dir = "/data/log"
index_file = "index.md"
highlight_style = "an-old-hope"
log_level = "Info"
max_cache_size = 52428800
port = 8080

[redirects]
# You can list as many redirects here as you'd like
# "original URL" = "new URI"
# 
# URIs should be absolute, except the left one should not have a preceding /
#
# Example:
# "original-uri/" = "/home/path/to/new/uri.md"
