document_root = "/Users/acbarrentine/Source/chimera-md/examples"
template_root = "/Users/acbarrentine/Source/chimera-md/templates"
style_root = "/Users/acbarrentine/Source/chimera-md/style"
icon_root = "/Users/acbarrentine/Source/chimera-md/icon"
search_index_dir = "/Users/acbarrentine/Source/chimera-md/search"
site_title = "Example journal"
index_file = "index.md"
site_lang = "en"
highlight_style = "a11y_dark"
generate_index = true
#log_level = "Debug"
max_cache_size = 52428800
port = 8080

[redirects]
"dialog-test/" = "/home/Dialog%20test%202.md"
